// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package apprpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Device struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	ServiceIp            string   `protobuf:"bytes,2,opt,name=serviceIp,proto3" json:"serviceIp,omitempty"`
	ServicePort          string   `protobuf:"bytes,3,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
	ServiceLaunched      bool     `protobuf:"varint,4,opt,name=serviceLaunched,proto3" json:"serviceLaunched,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Device) GetServiceIp() string {
	if m != nil {
		return m.ServiceIp
	}
	return ""
}

func (m *Device) GetServicePort() string {
	if m != nil {
		return m.ServicePort
	}
	return ""
}

func (m *Device) GetServiceLaunched() bool {
	if m != nil {
		return m.ServiceLaunched
	}
	return false
}

type Devices struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Devices) Reset()         { *m = Devices{} }
func (m *Devices) String() string { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()    {}
func (*Devices) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *Devices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices.Unmarshal(m, b)
}
func (m *Devices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices.Marshal(b, m, deterministic)
}
func (m *Devices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices.Merge(m, src)
}
func (m *Devices) XXX_Size() int {
	return xxx_messageInfo_Devices.Size(m)
}
func (m *Devices) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices.DiscardUnknown(m)
}

var xxx_messageInfo_Devices proto.InternalMessageInfo

func (m *Devices) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type AdbConnectParams struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdbConnectParams) Reset()         { *m = AdbConnectParams{} }
func (m *AdbConnectParams) String() string { return proto.CompactTextString(m) }
func (*AdbConnectParams) ProtoMessage()    {}
func (*AdbConnectParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *AdbConnectParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdbConnectParams.Unmarshal(m, b)
}
func (m *AdbConnectParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdbConnectParams.Marshal(b, m, deterministic)
}
func (m *AdbConnectParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdbConnectParams.Merge(m, src)
}
func (m *AdbConnectParams) XXX_Size() int {
	return xxx_messageInfo_AdbConnectParams.Size(m)
}
func (m *AdbConnectParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AdbConnectParams.DiscardUnknown(m)
}

var xxx_messageInfo_AdbConnectParams proto.InternalMessageInfo

func (m *AdbConnectParams) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AdbConnectParams) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type AdbShellParams struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdbShellParams) Reset()         { *m = AdbShellParams{} }
func (m *AdbShellParams) String() string { return proto.CompactTextString(m) }
func (*AdbShellParams) ProtoMessage()    {}
func (*AdbShellParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *AdbShellParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdbShellParams.Unmarshal(m, b)
}
func (m *AdbShellParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdbShellParams.Marshal(b, m, deterministic)
}
func (m *AdbShellParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdbShellParams.Merge(m, src)
}
func (m *AdbShellParams) XXX_Size() int {
	return xxx_messageInfo_AdbShellParams.Size(m)
}
func (m *AdbShellParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AdbShellParams.DiscardUnknown(m)
}

var xxx_messageInfo_AdbShellParams proto.InternalMessageInfo

func (m *AdbShellParams) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *AdbShellParams) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "apprpc.Empty")
	proto.RegisterType((*Message)(nil), "apprpc.Message")
	proto.RegisterType((*Device)(nil), "apprpc.Device")
	proto.RegisterType((*Devices)(nil), "apprpc.Devices")
	proto.RegisterType((*AdbConnectParams)(nil), "apprpc.AdbConnectParams")
	proto.RegisterType((*AdbShellParams)(nil), "apprpc.AdbShellParams")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0x5d, 0xf5, 0xcd, 0xea, 0xc8, 0xab, 0x65, 0x0e, 0xb2, 0x94, 0x1e, 0xc2, 0xf6, 0x92,
	0x53, 0x0e, 0x4a, 0x0b, 0x3d, 0xda, 0x3f, 0x94, 0x42, 0x0b, 0xa2, 0x9f, 0x60, 0x4d, 0x96, 0x1a,
	0x30, 0xc9, 0xb0, 0x9b, 0x16, 0xfa, 0x15, 0xfa, 0x61, 0xfa, 0x19, 0x8b, 0xd9, 0x5d, 0xb4, 0xd2,
	0xde, 0xe6, 0x99, 0x99, 0x27, 0x3c, 0xbf, 0xcc, 0xc2, 0x50, 0x11, 0xa5, 0x64, 0xea, 0xa6, 0xc6,
	0x48, 0x11, 0x19, 0xca, 0x24, 0x87, 0x7f, 0x0f, 0x25, 0x35, 0x1f, 0xf2, 0x12, 0xf8, 0x8b, 0xb6,
	0x56, 0xbd, 0x6a, 0x14, 0xc0, 0x4b, 0x57, 0x0a, 0x16, 0xb3, 0x64, 0xb8, 0x0a, 0x52, 0x7e, 0x32,
	0x88, 0xee, 0xf5, 0x7b, 0x91, 0x69, 0x9c, 0x42, 0x64, 0xb5, 0x29, 0xd4, 0xce, 0xef, 0x78, 0x85,
	0x17, 0x30, 0xb4, 0xda, 0xec, 0x57, 0x9e, 0x48, 0x74, 0xdb, 0xd1, 0xa1, 0x81, 0x31, 0x8c, 0xbc,
	0x58, 0xd6, 0xa6, 0x11, 0xbd, 0x76, 0x7e, 0xdc, 0xc2, 0x04, 0x26, 0x5e, 0x3e, 0xab, 0xb7, 0x2a,
	0xdb, 0xea, 0x5c, 0xf4, 0x63, 0x96, 0x0c, 0x56, 0xa7, 0x6d, 0x39, 0x07, 0xee, 0xb2, 0x58, 0x4c,
	0x80, 0xe7, 0xae, 0x14, 0x2c, 0xee, 0x25, 0xa3, 0xd9, 0x38, 0x75, 0x7c, 0xa9, 0xdb, 0x58, 0x85,
	0xb1, 0xbc, 0x86, 0xb3, 0x45, 0xbe, 0xb9, 0xab, 0xab, 0x4a, 0x67, 0xcd, 0x52, 0x19, 0x55, 0x5a,
	0x1c, 0x43, 0xb7, 0x20, 0x8f, 0xd1, 0x2d, 0x08, 0x11, 0xfa, 0xb4, 0x4f, 0xe7, 0xd2, 0xb7, 0xb5,
	0xbc, 0x85, 0xf1, 0x22, 0xdf, 0xac, 0xb7, 0x7a, 0xb7, 0xf3, 0xae, 0xbf, 0x7e, 0x80, 0x00, 0x9e,
	0xd5, 0x65, 0xa9, 0xaa, 0xdc, 0x7f, 0x20, 0xc8, 0xd9, 0x17, 0x03, 0x58, 0x10, 0xad, 0x1d, 0x07,
	0xa6, 0x00, 0x8f, 0xba, 0x09, 0x08, 0xff, 0x43, 0xe2, 0xf6, 0x1c, 0xe7, 0x93, 0x9f, 0x00, 0x56,
	0x76, 0xf0, 0x06, 0xe0, 0x10, 0x1d, 0x45, 0x58, 0x38, 0xc5, 0x39, 0x58, 0xfd, 0x3d, 0x65, 0x07,
	0xaf, 0x60, 0x10, 0xd2, 0xe3, 0xf4, 0xc8, 0x78, 0xc4, 0xf3, 0x8b, 0x6d, 0x13, 0xb5, 0x6f, 0x65,
	0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xc9, 0x18, 0xf6, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServiceClient interface {
	GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Devices, error)
	AdbConnect(ctx context.Context, in *AdbConnectParams, opts ...grpc.CallOption) (*Message, error)
	AdbShell(ctx context.Context, in *AdbShellParams, opts ...grpc.CallOption) (*Message, error)
}

type appServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServiceClient(cc *grpc.ClientConn) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Devices, error) {
	out := new(Devices)
	err := c.cc.Invoke(ctx, "/apprpc.AppService/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AdbConnect(ctx context.Context, in *AdbConnectParams, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/apprpc.AppService/AdbConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AdbShell(ctx context.Context, in *AdbShellParams, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/apprpc.AppService/AdbShell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
type AppServiceServer interface {
	GetDevices(context.Context, *Empty) (*Devices, error)
	AdbConnect(context.Context, *AdbConnectParams) (*Message, error)
	AdbShell(context.Context, *AdbShellParams) (*Message, error)
}

// UnimplementedAppServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAppServiceServer struct {
}

func (*UnimplementedAppServiceServer) GetDevices(ctx context.Context, req *Empty) (*Devices, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (*UnimplementedAppServiceServer) AdbConnect(ctx context.Context, req *AdbConnectParams) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdbConnect not implemented")
}
func (*UnimplementedAppServiceServer) AdbShell(ctx context.Context, req *AdbShellParams) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdbShell not implemented")
}

func RegisterAppServiceServer(s *grpc.Server, srv AppServiceServer) {
	s.RegisterService(&_AppService_serviceDesc, srv)
}

func _AppService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apprpc.AppService/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AdbConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdbConnectParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AdbConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apprpc.AppService/AdbConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AdbConnect(ctx, req.(*AdbConnectParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AdbShell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdbShellParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AdbShell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apprpc.AppService/AdbShell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AdbShell(ctx, req.(*AdbShellParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apprpc.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _AppService_GetDevices_Handler,
		},
		{
			MethodName: "AdbConnect",
			Handler:    _AppService_AdbConnect_Handler,
		},
		{
			MethodName: "AdbShell",
			Handler:    _AppService_AdbShell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
