
export enum Message {
  notifyOpenFolder = "Please open a folder",
  notifyNoEditor = "No text editor found",
  notifyScriptEmpty = "Script is empty",
  deviceBusy = "Device is busy",
  screenshotSuccess = "Screenshot success",
  screenshotFailure = "Screenshot failure",
  runScriptSuccess = "Run script success",
  runScriptFailure = "Run script failure",
  stopScriptSuccess = "Stop script success",
  stopScriptFailure = "Stop script failure",
  pauseScriptSuccess = "Pause script success",
  pauseScriptFailure = "Pause script failure",
  resumeScriptSuccess = "Resume script success",
  resumeScriptFailure = "Resume script failure",
  createNewSettingFile = "New robotmon-settings.json file created",
  robotmonSettingsFilename = "robotmon-settings.json",
  parseSettingsError = "Can not parse robotmon-settings.json",
  parseSettingsSuccess = "Reload robotmon-settings.json success",
}